### ISSUE TITLE
Integration with Rclone/Winfsp?

### ISSUE THREAD

**Issue by hanyoonLDA** [Backblaze-B2-Samples/b2fs4chia#13]
Hi guys! Was just wondering if you guys could point me in the right direction for possibly testing this out on a Windows environment with rclone and winfsp. Theoretically, it should work similarly, no?

**Comment by ppolewicz** [comment]
We tried configuring rclone for this and eventually we gave up and wrote a highly optimized version of the filesystem and you can see it in this repository. I heard that someone was able to tweak rclone so that quality checks are fast enough but then full proofs were not that fast and there is a limited amount of things you can do with rclone.

I suggest you try b2fs4chia on an Ubuntu virtual machine, it should be fairly easy to set up, though... if I had a lot of plots in B2 and I wanted to farm them, I'd use a linux cloud server with low latency to the B2 cluster I have the data on.

**Comment by hanyoonLDA** [comment]
Thanks for the prompt response! I seem to have bad luck with Ubuntu getting fully synced with the Chia blockchain. 0 for 2 so far, ahah. I'll try on a more reputable VPS provider and try again :)

**Comment by ppolewicz** [comment]
I heard Hetzner blocks port 8444 in fear of plotters destroying their NVMe drives (though it doesn't really make sense since it's full node that you run on 8444 and you don't need one for plotting. People do weird things in panic...).

I asked DigitalOcean if I can run a chia full node or plotter there, they said cryptocurrency mining (so the poor harvester!?) is forbidden there, I asked for clarification indicating a difference between PoW and PoT&S. Waiting 3 months for their response now, I guess they are still not decided :)

OVH cloud (not ovh dedicated/VM) panics when you do Chia stuff on their infra.

There is one more compute provider who I will not name, who has destroyed the hosts of one of my clients because the name of the machine was "chia" without warning. It wasn't plotting, but I think it might have had a full node running on it.

You need some compute power to get a full node up and running, a single core box with a weak CPU may not be enough. "Burst" instances might not be good either. YMMV.

**Comment by hanyoonLDA** [comment]
Linode has been super good to me. DO and Vultr I try to stay away from. They've gone full corporate mode.  

Quick question -- I've begun uploading the plots to my VM while I wait for the node to sync. Does the way in which I upload have any affect? Mainly the min. file chunk size, as I assume everything else should be default.

**Comment by hanyoonLDA** [comment]
Also, do you work for Backblaze? Ahaha, I just assumed you did. But wasn't sure.
